#!/bin/bash

BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^((bug|bugfix|enhancement|feature|fix|refactor)#([0-9]+)|(enhancement/epoch#[0-9]{10,})|dev|tags)$"

if ! [[ $BRANCH =~ $REGEX ]]; then
  message="Your commit was rejected due to branching name"
  message+="\nPlease don't commit directly to $BRANCH, "
  message+="or rename your branch with '(feature|bug|bugfix|fix)#id-issue' "
  message+="or 'enhancement/epoch#timestamp' syntaxes"
  echo -e "\033[1;31mERROR: $message\033[0m";
  exit 1
fi

REPO_DIR=$(git rev-parse --show-toplevel)

message="[Policy] Checking code in $REPO_DIR with black..."
# echo with color: https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797
echo -e "\033[1;34mInfo: $message\033[0m"

poetry run black --check $REPO_DIR && poetry run isort --check $REPO_DIR

if [ $? -eq 1 ]; then
    message="[Policy] Black|Isort check failed, "
    message+="please use black|isort to format your code."
    echo -e "\033[1;31mERROR: $message\033[0m";
    exit 1
else
    message="[Policy] Passed black|isort checking."
    echo -e "\033[1;32mOK: $message\033[0m"
    exit 0
fi
