[tool.poetry]
name = "incolume.py.fictus"
version = "0.3.0a2"
description = ""
authors = ["Britodfbr <britodfbr@gmail.com>"]
readme = "README.md"
packages = [{include = "incolume", from=""}]

[tool.poetry.dependencies]
python = "^3.8"
tomli = "^2.0.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
